/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

/**
 *
 * @author BLACKOUT
 */
public class CustomerLogin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLogin
     */
    public CustomerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        customerLoginLabel = new javax.swing.JLabel();
        customerUsernameLabel = new javax.swing.JLabel();
        customerUsernameTextField = new javax.swing.JTextField();
        customerPasswordField = new javax.swing.JPasswordField();
        customerPasswordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        homeButton.setText("GME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        customerLoginLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 30)); // NOI18N
        customerLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLoginLabel.setText("Customer Login");
        getContentPane().add(customerLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, -1));

        customerUsernameLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        customerUsernameLabel.setText("Username");
        getContentPane().add(customerUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        customerUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 190, -1));

        customerPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, -1));

        customerPasswordLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        customerPasswordLabel.setText("Password");
        getContentPane().add(customerPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 10, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        WelcomeMain obj1 = new WelcomeMain();
        obj1.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void customerUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerUsernameTextFieldActionPerformed

    private void customerPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerLoginLabel;
    private javax.swing.JPasswordField customerPasswordField;
    private javax.swing.JLabel customerPasswordLabel;
    private javax.swing.JLabel customerUsernameLabel;
    private javax.swing.JTextField customerUsernameTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
