/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import com.gme.Tables.Employee;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BLACKOUT
 */
public class Hire extends javax.swing.JFrame {

    /**
     * Creates new form Hire
     */
    public Hire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signOutButton = new javax.swing.JButton();
        hireButton = new javax.swing.JButton();
        stockDetailsButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        purchaseStockButton = new javax.swing.JButton();
        transferStockButton = new javax.swing.JButton();
        employeeHireLabel = new javax.swing.JLabel();
        employeePhoneNoLabel = new javax.swing.JLabel();
        employeeIDLabel = new javax.swing.JLabel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeNICLabel = new javax.swing.JLabel();
        employeeDOBLabel = new javax.swing.JLabel();
        employeeTitleLabel = new javax.swing.JLabel();
        employeeBranchLabel = new javax.swing.JLabel();
        employeeGenderLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        nicNumberTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        employeeGenderComboBox = new javax.swing.JComboBox();
        employeeBranchComboBox = new javax.swing.JComboBox();
        employeeTitleComboBox = new javax.swing.JComboBox();
        discardHireButton = new javax.swing.JButton();
        submitHireButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hire Employee");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signOutButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 13)); // NOI18N
        signOutButton.setText("Sign Out");
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 0, 127, -1));

        hireButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 13)); // NOI18N
        hireButton.setText("Hire");
        getContentPane().add(hireButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        stockDetailsButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 13)); // NOI18N
        stockDetailsButton.setText("Stock Details");
        stockDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stockDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        homeButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        homeButton.setText("GME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 10, 10));

        purchaseStockButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 13)); // NOI18N
        purchaseStockButton.setText("Purchase");
        purchaseStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseStockButtonActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseStockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        transferStockButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 13)); // NOI18N
        transferStockButton.setText("Transfer Stock");
        transferStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferStockButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transferStockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        employeeHireLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 30)); // NOI18N
        employeeHireLabel.setText("Employee Details");
        getContentPane().add(employeeHireLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        employeePhoneNoLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeePhoneNoLabel.setText("Password");
        getContentPane().add(employeePhoneNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        employeeIDLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeIDLabel.setText("First Name");
        getContentPane().add(employeeIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        employeeNameLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeNameLabel.setText("Last Name");
        getContentPane().add(employeeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        employeeNICLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeNICLabel.setText("NIC Number");
        getContentPane().add(employeeNICLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        employeeDOBLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeDOBLabel.setText("Username");
        getContentPane().add(employeeDOBLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        employeeTitleLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeTitleLabel.setText("Employee Job Title");
        getContentPane().add(employeeTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        employeeBranchLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeBranchLabel.setText("Employee Branch");
        getContentPane().add(employeeBranchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        employeeGenderLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeGenderLabel.setText("Employee Gender");
        getContentPane().add(employeeGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        lastNameTextField.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 320, -1));

        nicNumberTextField.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        getContentPane().add(nicNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 320, -1));

        firstNameTextField.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 320, -1));

        employeeGenderComboBox.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male", "Transgender", "Other" }));
        employeeGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeGenderComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(employeeGenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 160, 30));

        employeeBranchComboBox.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeBranchComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wellawatte", "Mount Lavinia", "Warehouse" }));
        getContentPane().add(employeeBranchComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        employeeTitleComboBox.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        employeeTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Salesman", "General Labor" }));
        getContentPane().add(employeeTitleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        discardHireButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 15)); // NOI18N
        discardHireButton.setText("Discard");
        getContentPane().add(discardHireButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        submitHireButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 15)); // NOI18N
        submitHireButton.setText("Submit");
        submitHireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitHireButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitHireButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 320, 30));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 320, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        WelcomeMain obj1 = new WelcomeMain();
        obj1.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void stockDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockDetailsButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        WelcomeMain obj1 = new WelcomeMain();
        obj1.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void purchaseStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseStockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseStockButtonActionPerformed

    private void transferStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferStockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferStockButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void employeeGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeGenderComboBoxActionPerformed

    private void submitHireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitHireButtonActionPerformed
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String nicNumber = nicNumberTextField.getText();
        String username = usernameTextField.getText();
        String password = passwordTextField.getText();
        String job_title = employeeTitleComboBox.getSelectedItem().toString();
        String office = employeeBranchComboBox.getSelectedItem().toString();
        
        Employee emp = new Employee(firstName, lastName, nicNumber, username, password, job_title, office); //Sets all the values of the text fields to the employee class
        
        try {
            
            emp.addNewEmployee(); //Adds new employee
            
            //Closes current window and reopens CEO window
            CEOMain obj = new CEOMain();
            obj.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(Hire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            
            Logger.getLogger(Hire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitHireButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton discardHireButton;
    private javax.swing.JComboBox employeeBranchComboBox;
    private javax.swing.JLabel employeeBranchLabel;
    private javax.swing.JLabel employeeDOBLabel;
    private javax.swing.JComboBox employeeGenderComboBox;
    private javax.swing.JLabel employeeGenderLabel;
    private javax.swing.JLabel employeeHireLabel;
    private javax.swing.JLabel employeeIDLabel;
    private javax.swing.JLabel employeeNICLabel;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JLabel employeePhoneNoLabel;
    private javax.swing.JComboBox employeeTitleComboBox;
    private javax.swing.JLabel employeeTitleLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton hireButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField nicNumberTextField;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton purchaseStockButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton stockDetailsButton;
    private javax.swing.JButton submitHireButton;
    private javax.swing.JButton transferStockButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
