/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import com.gme.Tables.Employee;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BLACKOUT
 */
public class StaffLogin extends javax.swing.JFrame {
private static int actionINT = 4;
    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffLoginLabel = new javax.swing.JLabel();
        staffUsernameLabel = new javax.swing.JLabel();
        staffPasswordLabel = new javax.swing.JLabel();
        staffUsernameTextField = new javax.swing.JTextField();
        staffPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        staffLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffLoginLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 30)); // NOI18N
        staffLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffLoginLabel.setText("Staff Login");
        getContentPane().add(staffLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, -1));

        staffUsernameLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        staffUsernameLabel.setText("Username");
        getContentPane().add(staffUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        staffPasswordLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        staffPasswordLabel.setText("Password");
        getContentPane().add(staffPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        staffUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(staffUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 190, -1));

        staffPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(staffPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 10, 10));

        homeButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        homeButton.setText("GME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        staffLoginButton.setFont(new java.awt.Font("Nanum Myeongjo", 0, 13)); // NOI18N
        staffLoginButton.setText("Login");
        staffLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(staffLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void staffUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffUsernameTextFieldActionPerformed

    private void staffPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPasswordFieldActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        WelcomeMain obj1 = new WelcomeMain();
        obj1.setVisible(true);
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void staffLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffLoginButtonActionPerformed
        String username = staffUsernameTextField.getText();
        String password = new String (staffPasswordField.getPassword());
        Employee emp = new Employee();
        //do{
    try {
        if(emp.validateLogin(username, password)){ //Validates if the user has entered the correct username and password
            
            String job_title = emp.getTitle();
            String office = emp.getOffice();
            
            if(job_title.equals("CEO")){ //Actions when the user is the CEO
                
                CEOMain obj = new CEOMain();
                obj.setVisible(true);
                this.dispose();
            }else if(job_title.equals("Manager")){ //Actions when the user is a Manager
                
                if(office.equals("Wellawatte")){ //If the Manager is working at the Wellawatte branch
                    
                    ManagerMain obj = new ManagerMain();
                    obj.setVisible(true);
                    this.dispose();
                }else if(office.equals("Mount Lavinia")){ //If the Manager is workig at the ML branch
                    
                    ManagerMT obj = new ManagerMT();
                    obj.setVisible(true);
                    this.dispose();
                }
            }else if(job_title.equals("Salesman")){//Actions when the user is a salesman
                
                if(office.equals("Wellawatte")){
                    
                    Salesmen obj = new Salesmen();
                    obj.setVisible(true);
                    this.dispose();
                }else if(office.equals("Mount Lavinia")){
                    
                    SalesmenMT obj = new SalesmenMT();
                    obj.setVisible(true);
                    this.dispose();
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Invalid username or password");
            staffUsernameTextField.setText("");
            staffPasswordField.setText("");
        }
       
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(StaffLogin.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(StaffLogin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_staffLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton staffLoginButton;
    private javax.swing.JLabel staffLoginLabel;
    private javax.swing.JPasswordField staffPasswordField;
    private javax.swing.JLabel staffPasswordLabel;
    private javax.swing.JLabel staffUsernameLabel;
    private javax.swing.JTextField staffUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
