/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

/**
 *
 * @author BLACKOUT
 */
public class StaffLogin extends javax.swing.JFrame {

    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gmeLogoLabel = new javax.swing.JLabel();
        staffLoginLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        staffUsernameTextField = new javax.swing.JTextField();
        staffPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gmeLogoLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        gmeLogoLabel.setText("GME");
        getContentPane().add(gmeLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 90, 40));

        staffLoginLabel.setFont(new java.awt.Font("Nanum Myeongjo", 0, 30)); // NOI18N
        staffLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffLoginLabel.setText("Staff Login");
        getContentPane().add(staffLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, -1));

        jLabel1.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nanum Myeongjo", 0, 20)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        staffUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(staffUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 190, -1));

        staffPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(staffPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void staffUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffUsernameTextFieldActionPerformed

    private void staffPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gmeLogoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel staffLoginLabel;
    private javax.swing.JPasswordField staffPasswordField;
    private javax.swing.JTextField staffUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
